apiVersion: v1
kind: Service
metadata:
  name: aceest-canary-service
  namespace: aceest-devops
spec:
  type: NodePort
  selector:
    app: aceest-canary-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30082