apiVersion: v1
kind: Service
metadata:
  name: aceest-shadow-main-service
  namespace: aceest-devops
spec:
  type: NodePort
  selector:
    app: aceest-shadow-app
    track: main
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30083